<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="TAHIR" failures="1" tests="4" name="Test" time="54.259" errors="0" timestamp="2022-11-16T11:38:34 IST">
  <testcase classname="test.SwagLabsLoginTest" name="swagLabsLoginTestWithValidCredentials" time="1.569"/>
  <testcase classname="test.SwagLabsLoginTest" name="swagLabsLoginTestWithValidCredentials" time="0.965">
    <failure type="java.lang.AssertionError" message="expected [https://www.saucedemo.com/inventory.html] but found [https://www.saucedemo.com/]">
      <![CDATA[java.lang.AssertionError: expected [https://www.saucedemo.com/inventory.html] but found [https://www.saucedemo.com/]
at test.SwagLabsLoginTest.swagLabsLoginTestWithValidCredentials(SwagLabsLoginTest.java:58)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- swagLabsLoginTestWithValidCredentials -->
  <testcase classname="test.SwagLabsLoginTest" name="swagLabsLoginTestWithValidCredentials" time="1.23"/>
  <testcase classname="test.SwagLabsLoginTest" name="swagLabsLoginTestWithValidCredentials" time="6.473"/>
</testsuite> <!-- Test -->
